### PR TITLE
[WIP] Enable tabs for report

### PR DESCRIPTION
**Pull request by SeanFeldman**
Implements issue #53 

- [x] Emit extra html for tabs and static CSS for styling
- [x] Fallback to original rendering if CSS is missing (offline HTML w/o CSS)
- [x] Deal with multiple comparison sets

[Sample data](http://apicomparer.particular.net/compare/EntityFramework/6.0.0...6.1.3)

### CODE REVIEW

**Comment by SeanFeldman** [comment]
There's an issue with some packages - # of targets and length of their names generates too many long tabs. Example: `.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+aspnetcore50`.

Even stripping all non alphanumerics would still be an issue.
image
Any good suggestions for tab names @andreasohlund ?

**Comment by SeanFeldman** [comment]
What if we do a TOC on top?

**Comment by SimonCropp** [comment]
does this help at all http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY/preview  ?

**Comment by SeanFeldman** [comment]
Not sure how. The list doesn't look complete :( Wasn't able to find anything that would contain `aspnetcore50`
Haven't realized these profiles are such a mess.

**Comment by andreasohlund** [comment]
@SimonCropp are you saying to only display the profile, eg `Profile344` , as the heading? (with a potential tooltip showing the full name)

**Comment by SimonCropp** [comment]
@andreasohlund not really. Was thinking some extra info might help us think of a better it doesnt look like it.


@SeanFeldman and yes the profiles are a huge mess

**Comment by SeanFeldman** [comment]
@andreasohlund we can't use `ProfileABC` since not all profiles have a designated name (not listed [here](http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY/preview)).

**Comment by andreasohlund** [comment]
Just shorten them with a "..." + tooltip for now?

**Comment by SeanFeldman** [comment]
Shortening is problematic. Here's an example (extreme one, but still). Original names of difference sets:
`.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+aspnetcore50`
`.NETPortable,Version=v0.0,Profile=net45+wp80+win8`

After shortening to 20 alpha numerics only:
`NETPortableVersionv0...`
`NETPortableVersionv0...`

A full comparison for newtonsoft.json/5.0.8...6.0.8 looks like the following:
image

I decide to take the following approach.
 -  If number of sets is less than 5, show the whole name
image

 - Otherwise show `Set #X` and a tooltip on hover over to show the full description
image

**Comment by SeanFeldman** [comment]
@ParticularLabs/apicomparer please review

**Comment by andreasohlund** [comment]
:+1:

**Pull request merged**
