### PR TITLE
adding views to support main page with GTM

### PR DESCRIPTION
**Pull request by SeanFeldman**
Currently we don't track whoever is coming to the main page. 
Added home view to include GTM.

What would be nice is to tie into view engine to return comparisons as views as well.
@ParticularLabs/apicomparer any ideas/thoughts?

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Related to #20

**Comment by andreasohlund** [comment]
Yea, +1 to get gtm on the comparisons as well.

**Comment by danielmarbach** [comment]
We need to revamp the comparison page anyway. Why not include it then?

**Comment by SeanFeldman** [comment]
@danielmarbach it's [already included](https://github.com/ParticularLabs/APIComparer/blob/master/APIComparer.Website/Comparisons/CompareRunning.html#L8).

**Pull request merged**
